bugfix: create maker BUY order M, partial fill F1, partial fill F2, create taker SELL order H1 for hedging F1+F2, partial fill F3 (F3 < hedging threshold), maker order complete filled. H1 completed filled. currently active_maker_limit_orders no longer contains M. so in did_complete_sell_order/did_complete_buy_order, we could not delete the maker order entity in records.
********************
====>  BGVUT5f8e19036efac7de6ba20a521c2     148662403767
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - did_complete_sell_order: maker_order_id: BGVUT5f8e19036efac7de6ba20a521c2 partial hedged by taker order_id: AAc484720aSGVUT5f8e1903824e07de6ba20a521c262b222cda37b12a614 [clock=2023-04-09 06:42:34.400000095+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - did_complete_sell_order: maker_filled_trades: ['148662069802_1'] of maker_order_id: BGVUT5f8e1855dd0647de6ba20a521c2 fully hedged. [clock=2023-04-09 06:42:34.400000095+00:00]

connector.client_order_tracker - INFO - The BUY order BGVUT5f8e19036efac7de6ba20a521c2 amounting to 262.70/300.00 GRV has been filled.
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - did_fill_order: order_id BGVUT5f8e19036efac7de6ba20a521c2 [clock=2023-04-09 06:42:34.400000095+00:00]
core.event.event_reporter - EVENT_LOG - {"timestamp": 1681022554.4, "order_id": "BGVUT5f8e19036efac7de6ba20a521c2", "trading_pair": "GRV-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "1.0132", "amount": "130.61", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "-0.397002156"}]}, "exchange_trade_id": "148662403767_2", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "hotbit"}

connector.client_order_tracker - INFO - The BUY order BGVUT5f8e19036efac7de6ba20a521c2 amounting to 267.29/300.00 GRV has been filled.
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - did_fill_order: order_id BGVUT5f8e19036efac7de6ba20a521c2 [clock=2023-04-09 06:42:34.400000095+00:00]
core.event.event_reporter - EVENT_LOG - {"timestamp": 1681022554.4, "order_id": "BGVUT5f8e19036efac7de6ba20a521c2", "trading_pair": "GRV-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "1.0132", "amount": "4.59", "trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "-0.013951764"}]}, "exchange_trade_id": "148662403767_3", "leverage": 1, "position": "NIL","event_name": "OrderFilledEvent", "event_source": "hotbit"}

connector.exchange.hotbit.hotbit_exchange.HotbitExchange - INFO - create_trade_update fill order_id:BGVUT5f8e19036efac7de6ba20a521c2, trade_id:148662403767_4,current_deal_stock:32.71,current_deal_stock:33.141772, current_fee:-0.099425316
connector.client_order_tracker - INFO - The BUY order BGVUT5f8e19036efac7de6ba20a521c2 amounting to 300.00/300.00 GRV has been filled.
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - did_fill_order: order_id BGVUT5f8e19036efac7de6ba20a521c2 [clock=2023-04-09 06:42:34.400000095+00:00]
core.event.event_reporter - EVENT_LOG - {"timestamp": 1681022554.4, "order_id": "BGVUT5f8e19036efac7de6ba20a521c2", "trading_pair": "GRV-USDT", "trade_type": "TradeType.BUY", "order_type": "OrderType.LIMIT_MAKER", "price": "1.0132", "amount": "32.71","trade_fee": {"percent": "0", "percent_token": "USDT", "flat_fees": [{"token": "USDT", "amount": "-0.099425316"}]}, "exchange_trade_id": "148662403767_4", "leverage": 1, "position": "NIL", "event_name": "OrderFilledEvent", "event_source": "hotbit"}

strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - check_and_hedge_orders: hedge_buy_under_checking: False, hedge_sell_under_checking: False
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - orig maker order BGVUT5f8e19036efac7de6ba20a521c2, expected hedge price: 1.0173 [clock=2023-04-09 06:42:34.400000095+00:00]

====> hedge 148662403767_2
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - Calculated by HB order_price: 1.0174 [clock=2023-04-09 06:42:34.400000095+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - Slippage buffer adjusted order_price: 1.0153 [clock=2023-04-09 06:42:34.400000095+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - place_order: huobi: level -1, OrderType.LIMIT, taker, sell, amount 130.6100, price 1.0153, exp NaN [clock=2023-04-09 06:42:34.400000095+00:00]

====>  place taker order  AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614   for 148662403767_2
strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - place_order: order_id AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614 [clock=2023-04-09 06:42:34.400000095+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - place_order: taker_order_id: AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614, hedge maker_order_ids: ['BGVUT5f8e19036efac7de6ba20a521c2'], maker_exchange_trade_ids: ['148662403767_2'] [clock=2023-04-09 06:42:34.400000095+00:00]

====> for 148662403767_3

strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - check_and_hedge_orders: hedge_buy_under_checking: False, hedge_sell_under_checking: False
strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - buy_fill_quantity (4.59) < hedge_min_quantity (50.0), skip
strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - hedge_buy_pending: ['148662403767_3']

strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - check_and_hedge_orders: hedge_buy_under_checking: False, hedge_sell_under_checking: False
strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - buy_fill_quantity (37.30) < hedge_min_quantity (50.0), skip
strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - hedge_buy_pending: ['148662403767_3', '148662403767_4']

====> maker order completely filled
connector.client_order_tracker - INFO - BUY order BGVUT5f8e19036efac7de6ba20a521c2 completely filled.

strategy.cross_exchange_market_making.cross_exchange_market_making - DEBUG - did_complete_sell_order: order_id AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614 [clock=2023-04-09 06:42:34.800000191+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - (GRV-USDT) Taker SELL order AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614 for (130.61 GRV @ 1.0173 USDT,132.869553 USDT) completely filled. [clock=2023-04-09 06:42:34.800000191+00:00]
strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - did_complete_sell_order: maker_filled_trades: ['148662403767_1', '148662403767_2', '148662403767_3', '148662403767_4'] of maker_order_id: BGVUT5f8e19036efac7de6ba20a521c2 fully hedged.

strategy.cross_exchange_market_making.cross_exchange_market_making - INFO - (did_complete_sell_order: taker order_id: AAc484720aSGVUT5f8e1903c21597de6ba20a521c262b222cda37b12a614 hedged maker_filled_trades: ['148662403767_2'] [clock=2023-04-09 06:42:34.800000191+00:00]

strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - Multiple buy maker orders fills
strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - maker_order_ids=['BGVUT5f8e19036efac7de6ba20a521c2', 'BGVUT5f8e19036efac7de6ba20a521c2', 'BGVUT5f8e1e8c35fcc7de6ba20a52c2'], maker_exchange_trade_ids=['148662403767_3', '148662403767_4', '148665389181_1']
strategy.cross_exchange_market_making.cross_exchange_market_making - WARNING - hedge_buy_pending: ['148662403767_3', '148662403767_4', '148665389181_1']
strategy.cross_exchange_market_making.cross_exchange_market_making - ERROR - Unexpected error. [clock=2023-04-09 07:07:32.800000191+00:00]
Traceback (most recent call last):
  File "/home/tony/work/hummingbot/hotbit_huobi_grv/hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.py", line 681, in hedge_filled_maker_order
    await self.check_and_hedge_orders(market_pair)
  File "/home/tony/work/hummingbot/hotbit_huobi_grv/hummingbot/strategy/cross_exchange_market_making/cross_exchange_market_making.py", line 1054, in check_and_hedge_orders
    self.log_with_clock(logging.DEBUG, f"orig maker order {order_id}, expected hedge price: {self.expected_hedging_prices[order_id]}")
KeyError: 'BGVUT5f8e19036efac7de6ba20a521c2'

********************

Signed-off-by: yiliang.teng <ylteng@outlook.com>